import type { ExtendedPanel, TemplateVariation } from './template-registry'
import { createTemplateMetadata } from './template-converter'
import { COMMON_DEPENDENCIES } from './template-registry'

// Media Grid templates
const MEDIA_GRID_TEMPLATES = [
  { id: 1, name: "Responsive Grid", style: "minimal" as const, code: 'export default function MediaGrid() {\n  const items = Array.from({ length: 8 }, (_, i) => ({ id: i + 1, type: \'image\' }))\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">\n        {items.map(item => (\n          <div key={item.id} className="bg-accent rounded-lg aspect-square flex items-center justify-center">\n            <span className="text-muted-foreground">Media {item.id}</span>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "Masonry Grid", style: "modern" as const, code: 'export default function MasonryGrid() {\n  const items = Array.from({ length: 12 }, (_, i) => ({ id: i + 1, span: i % 3 === 0 ? \'col-span-2 row-span-2\' : \'\' }))\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 auto-rows-max">\n        {items.map(item => (\n          <div key={item.id} className={"bg-accent rounded-lg aspect-square flex items-center justify-center " + item.span}>\n            <span className="text-muted-foreground">Item {item.id}</span>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 3, name: "Justified Grid", style: "classic" as const, code: 'export default function JustifiedGrid() {\n  const items = Array.from({ length: 9 }, (_, i) => ({ id: i + 1 }))\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="flex flex-wrap gap-2">\n        {items.map(item => (\n          <div key={item.id} className="flex-1 min-w-[150px] h-32 bg-accent rounded-lg flex items-center justify-center">\n            <span className="text-muted-foreground">Item {item.id}</span>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 4, name: "Pinterest Grid", style: "bold" as const, code: 'export default function PinterestGrid() {\n  const items = Array.from({ length: 15 }, (_, i) => ({ id: i + 1, height: Math.random() > 0.5 ? \'h-48\' : \'h-64\' }))\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="columns-2 md:columns-3 lg:columns-4 gap-4">\n        {items.map(item => (\n          <div key={item.id} className={"bg-accent rounded-lg mb-4 flex items-center justify-center " + item.height}>\n            <span className="text-muted-foreground">Pin {item.id}</span>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' }
]

// Video Gallery templates
const VIDEO_GALLERY_TEMPLATES = [
  { id: 1, name: "Grid View", style: "minimal" as const, code: 'export default function VideoGridGallery() {\n  const videos = Array.from({ length: 6 }, (_, i) => ({ id: i + 1, title: "Video " + (i + 1), duration: "5:30" }))\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">\n        {videos.map(video => (\n          <div key={video.id} className="group relative bg-black rounded-lg overflow-hidden aspect-video cursor-pointer">\n            <div className="absolute inset-0 bg-black/40 group-hover:bg-black/60 transition-colors flex items-center justify-center">\n              <div className="w-12 h-12 bg-primary rounded-full flex items-center justify-center">▶</div>\n            </div>\n            <div className="absolute bottom-2 right-2 px-2 py-1 bg-black/80 text-white text-xs rounded">{video.duration}</div>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "List View", style: "modern" as const, code: 'export default function VideoListGallery() {\n  const videos = Array.from({ length: 5 }, (_, i) => ({ id: i + 1, title: "Video " + (i + 1), views: Math.floor(Math.random() * 10000) }))\n  return (\n    <div className="w-full bg-background p-6 space-y-3">\n      {videos.map(video => (\n        <div key={video.id} className="flex gap-4 p-3 bg-accent rounded-lg hover:bg-accent/80 transition-colors cursor-pointer">\n          <div className="w-24 h-16 bg-black rounded flex items-center justify-center text-white">▶</div>\n          <div className="flex-1">\n            <h3 className="font-medium text-foreground">{video.title}</h3>\n            <p className="text-sm text-muted-foreground">{video.views.toLocaleString()} views</p>\n          </div>\n        </div>\n      ))}\n    </div>\n  )\n}' },
  { id: 3, name: "Featured View", style: "classic" as const, code: 'export default function VideoFeaturedGallery() {\n  const featured = { id: 1, title: "Featured Video", views: 50000 }\n  const videos = Array.from({ length: 4 }, (_, i) => ({ id: i + 2, title: "Video " + (i + 2) }))\n  return (\n    <div className="w-full bg-background p-6 space-y-6">\n      <div className="relative bg-black rounded-lg overflow-hidden aspect-video">\n        <div className="absolute inset-0 flex items-center justify-center text-white text-4xl">▶</div>\n        <div className="absolute bottom-4 left-4 text-white">\n          <h2 className="text-xl font-bold">{featured.title}</h2>\n          <p className="text-sm">{featured.views.toLocaleString()} views</p>\n        </div>\n      </div>\n      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">\n        {videos.map(video => (\n          <div key={video.id} className="bg-black rounded-lg aspect-video flex items-center justify-center text-white cursor-pointer hover:opacity-80">\n            ▶\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 4, name: "Category View", style: "bold" as const, code: 'export default function VideoCategoryGallery() {\n  const categories = [\n    { name: "Tutorials", count: 24 },\n    { name: "Reviews", count: 18 },\n    { name: "Vlogs", count: 42 },\n    { name: "Music", count: 31 }\n  ]\n  return (\n    <div className="w-full bg-background p-6">\n      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">\n        {categories.map(cat => (\n          <div key={cat.name} className="bg-gradient-to-br from-primary to-primary/60 rounded-lg p-6 text-white cursor-pointer hover:shadow-lg transition-shadow">\n            <h3 className="text-lg font-bold">{cat.name}</h3>\n            <p className="text-sm opacity-90">{cat.count} videos</p>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}' }
]

// Audio Player templates
const AUDIO_PLAYER_TEMPLATES = [
  { id: 1, name: "Mini Player", style: "minimal" as const, code: 'export default function MiniAudioPlayer() {\n  return (\n    <div className="w-full max-w-sm bg-accent rounded-lg p-4">\n      <div className="flex items-center gap-3">\n        <button className="p-2 bg-primary text-primary-foreground rounded-full hover:bg-primary/90">▶</button>\n        <div className="flex-1">\n          <p className="text-sm font-medium text-foreground">Now Playing</p>\n          <p className="text-xs text-muted-foreground">Artist Name</p>\n        </div>\n        <span className="text-xs text-muted-foreground">3:45</span>\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "Full Player", style: "modern" as const, code: 'export default function FullAudioPlayer() {\n  return (\n    <div className="w-full max-w-md bg-gradient-to-br from-primary to-primary/60 rounded-lg p-6 text-white">\n      <div className="text-center mb-6">\n        <div className="w-32 h-32 bg-white/20 rounded-lg mx-auto mb-4 flex items-center justify-center text-4xl">♪</div>\n        <h3 className="text-xl font-bold">Song Title</h3>\n        <p className="text-sm opacity-90">Artist Name</p>\n      </div>\n      <div className="space-y-4">\n        <div className="h-1 bg-white/30 rounded-full"><div className="h-full w-1/3 bg-white rounded-full"></div></div>\n        <div className="flex justify-between text-xs"><span>1:15</span><span>3:45</span></div>\n        <div className="flex justify-center gap-4">\n          <button className="p-2 hover:bg-white/20 rounded-full">⏮</button>\n          <button className="p-3 bg-white text-primary rounded-full hover:bg-white/90">▶</button>\n          <button className="p-2 hover:bg-white/20 rounded-full">⏭</button>\n        </div>\n      </div>\n    </div>\n  )\n}' },
  { id: 3, name: "Playlist", style: "classic" as const, code: 'export default function AudioPlaylist() {\n  const songs = Array.from({ length: 5 }, (_, i) => ({ id: i + 1, title: "Song " + (i + 1), artist: "Artist", duration: "3:45" }))\n  return (\n    <div className="w-full max-w-md bg-accent rounded-lg p-4 space-y-2">\n      {songs.map((song, idx) => (\n        <div key={song.id} className={"flex items-center gap-3 p-3 rounded-lg cursor-pointer " + (idx === 0 ? "bg-primary text-primary-foreground" : "hover:bg-background")}>\n          <span className="text-sm font-medium">{idx + 1}</span>\n          <div className="flex-1">\n            <p className="text-sm font-medium">{song.title}</p>\n            <p className="text-xs opacity-75">{song.artist}</p>\n          </div>\n          <span className="text-xs">{song.duration}</span>\n        </div>\n      ))}\n    </div>\n  )\n}' },
  { id: 4, name: "Podcast Player", style: "bold" as const, code: 'export default function PodcastPlayer() {\n  return (\n    <div className="w-full max-w-md bg-background border border-border rounded-lg p-6">\n      <div className="flex gap-4 mb-4">\n        <div className="w-16 h-16 bg-accent rounded-lg flex items-center justify-center text-2xl">🎙</div>\n        <div className="flex-1">\n          <h3 className="font-bold text-foreground">Podcast Title</h3>\n          <p className="text-sm text-muted-foreground">Episode 42</p>\n          <p className="text-xs text-muted-foreground mt-1">Published 2 days ago</p>\n        </div>\n      </div>\n      <div className="space-y-3">\n        <div className="h-1 bg-border rounded-full"><div className="h-full w-2/5 bg-primary rounded-full"></div></div>\n        <div className="flex justify-between text-xs text-muted-foreground"><span>24:30</span><span>60:00</span></div>\n        <div className="flex justify-center gap-2">\n          <button className="px-3 py-1 text-xs bg-accent hover:bg-accent/80 rounded">-15s</button>\n          <button className="p-2 bg-primary text-primary-foreground rounded-full hover:bg-primary/90">▶</button>\n          <button className="px-3 py-1 text-xs bg-accent hover:bg-accent/80 rounded">+15s</button>\n        </div>\n      </div>\n    </div>\n  )\n}' }
]

// Image Comparison templates
const IMAGE_COMPARISON_TEMPLATES = [
  { id: 1, name: "Slider", style: "minimal" as const, code: 'export default function ImageComparisonSlider() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="relative bg-accent rounded-lg overflow-hidden aspect-video">\n        <div className="absolute inset-0 flex items-center justify-center text-muted-foreground">Before Image</div>\n        <div className="absolute inset-0 w-1/2 flex items-center justify-center text-muted-foreground">After Image</div>\n        <div className="absolute top-0 bottom-0 left-1/2 w-1 bg-primary cursor-col-resize"></div>\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "Side by Side", style: "modern" as const, code: 'export default function ImageComparisonSideBySide() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="grid grid-cols-2 gap-4">\n        <div className="bg-accent rounded-lg aspect-video flex items-center justify-center text-muted-foreground">Before</div>\n        <div className="bg-accent rounded-lg aspect-video flex items-center justify-center text-muted-foreground">After</div>\n      </div>\n    </div>\n  )\n}' },
  { id: 3, name: "Overlay", style: "classic" as const, code: 'export default function ImageComparisonOverlay() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="relative bg-accent rounded-lg overflow-hidden aspect-video">\n        <div className="absolute inset-0 flex items-center justify-center text-muted-foreground">Before</div>\n        <div className="absolute inset-0 w-3/4 flex items-center justify-center text-muted-foreground opacity-75">After</div>\n      </div>\n    </div>\n  )\n}' },
  { id: 4, name: "Hover", style: "bold" as const, code: 'export default function ImageComparisonHover() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="relative bg-accent rounded-lg overflow-hidden aspect-video group cursor-pointer">\n        <div className="absolute inset-0 flex items-center justify-center text-muted-foreground">Before</div>\n        <div className="absolute inset-0 flex items-center justify-center text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity">After</div>\n      </div>\n    </div>\n  )\n}' }
]

// Media Upload templates
const MEDIA_UPLOAD_TEMPLATES = [
  { id: 1, name: "Drag Drop", style: "minimal" as const, code: 'export default function DragDropUpload() {\n  return (\n    <div className="w-full max-w-md md:max-w-lg">\n      <div className="border-2 border-dashed border-border rounded-lg p-8 md:p-12 text-center hover:border-primary transition-colors cursor-pointer">\n        <div className="text-4xl md:text-5xl mb-2">📁</div>\n        <p className="font-medium text-foreground">Drag files here</p>\n        <p className="text-sm text-muted-foreground">or click to browse</p>\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "With Preview", style: "modern" as const, code: 'export default function UploadWithPreview() {\n  return (\n    <div className="w-full max-w-md md:max-w-lg space-y-4">\n      <div className="border-2 border-dashed border-border rounded-lg p-8 md:p-12 text-center">\n        <p className="text-sm text-muted-foreground">Drop files here</p>\n      </div>\n      <div className="grid grid-cols-3 md:grid-cols-4 gap-2">\n        {[1,2,3].map(i => (\n          <div key={i} className="bg-accent rounded-lg aspect-square flex items-center justify-center text-muted-foreground">Preview</div>\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 3, name: "Progress", style: "classic" as const, code: 'export default function UploadProgress() {\n  return (\n    <div className="w-full max-w-md md:max-w-lg space-y-3">\n      <div className="p-4 md:p-6 bg-accent rounded-lg">\n        <div className="flex justify-between mb-2">\n          <span className="text-sm font-medium text-foreground">Uploading...</span>\n          <span className="text-sm text-muted-foreground">65%</span>\n        </div>\n        <div className="h-2 bg-border rounded-full overflow-hidden">\n          <div className="h-full w-2/3 bg-primary rounded-full transition-all"></div>\n        </div>\n      </div>\n    </div>\n  )\n}' },
  { id: 4, name: "Multiple", style: "bold" as const, code: 'export default function MultipleUpload() {\n  return (\n    <div className="w-full max-w-md md:max-w-lg space-y-3">\n      {[1,2,3].map(i => (\n        <div key={i} className="flex items-center gap-3 p-3 md:p-4 bg-accent rounded-lg">\n          <div className="w-10 h-10 md:w-12 md:h-12 bg-background rounded flex items-center justify-center">📄</div>\n          <div className="flex-1">\n            <p className="text-sm font-medium text-foreground">file{i}.pdf</p>\n            <p className="text-xs text-muted-foreground">2.4 MB</p>\n          </div>\n          <span className="text-xs text-accent-foreground">✓</span>\n        </div>\n      ))}\n    </div>\n  )\n}' }
]

// Slideshow templates
const SLIDESHOW_TEMPLATES = [
  { id: 1, name: "Auto", style: "minimal" as const, code: 'export default function AutoSlideshow() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="bg-accent rounded-lg aspect-video flex items-center justify-center text-muted-foreground">Slide 1</div>\n      <div className="flex justify-center gap-2 mt-4">\n        {[1,2,3,4].map(i => (\n          <button key={i} className={"h-2 rounded-full transition-all " + (i === 1 ? "w-8 bg-primary" : "w-2 bg-border")} />\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 2, name: "Manual", style: "modern" as const, code: 'export default function ManualSlideshow() {\n  return (\n    <div className="w-full max-w-2xl">\n      <div className="bg-accent rounded-lg aspect-video flex items-center justify-center text-muted-foreground">Slide 1</div>\n      <div className="flex justify-between items-center mt-4">\n        <button className="px-4 py-2 bg-background border border-border rounded-lg hover:bg-accent">← Prev</button>\n        <span className="text-sm text-muted-foreground">1 / 4</span>\n        <button className="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90">Next →</button>\n      </div>\n    </div>\n  )\n}' },
  { id: 3, name: "Thumbnail", style: "classic" as const, code: 'export default function ThumbnailSlideshow() {\n  return (\n    <div className="w-full max-w-2xl space-y-4">\n      <div className="bg-accent rounded-lg aspect-video flex items-center justify-center text-muted-foreground">Main Slide</div>\n      <div className="grid grid-cols-4 gap-2">\n        {[1,2,3,4].map(i => (\n          <button key={i} className={"rounded-lg aspect-square border-2 " + (i === 1 ? "border-primary" : "border-border") + " bg-accent"} />\n        ))}\n      </div>\n    </div>\n  )\n}' },
  { id: 4, name: "Full Screen", style: "bold" as const, code: 'export default function FullScreenSlideshow() {\n  return (\n    <div className="w-full h-screen bg-black flex items-center justify-center relative">\n      <div className="text-white text-4xl">Slide 1</div>\n      <button className="absolute top-4 right-4 text-white text-2xl">✕</button>\n      <button className="absolute left-4 top-1/2 -translate-y-1/2 text-white text-3xl">❮</button>\n      <button className="absolute right-4 top-1/2 -translate-y-1/2 text-white text-3xl">❯</button>\n    </div>\n  )\n}' }
]

function createMediaPanel(id: string, name: string, templates: any[]): ExtendedPanel {
  const variations: TemplateVariation[] = templates.map((template) => ({
    id: `${id}-${template.style}-${template.id}`,
    name: template.name,
    description: `${name} - ${template.name} variation`,
    style: template.style,
    code: template.code,
    metadata: createTemplateMetadata({
      complexity: 'simple',
      features: [name, 'Responsive', 'Interactive'],
      useCases: ['Media Display', 'Content Showcase'],
      dependencies: [...COMMON_DEPENDENCIES.core]
    })
  }))

  return {
    id,
    name,
    description: `${name} component templates`,
    category: 'media-gallery',
    variations,
    tags: ['media', 'gallery']
  }
}

export const MEDIA_GRID_PANEL_WITH_VARIATIONS = createMediaPanel('media-grid', 'Media Grid', MEDIA_GRID_TEMPLATES)
export const VIDEO_GALLERY_PANEL_WITH_VARIATIONS = createMediaPanel('video-gallery', 'Video Gallery', VIDEO_GALLERY_TEMPLATES)
export const AUDIO_PLAYER_PANEL_WITH_VARIATIONS = createMediaPanel('audio-player', 'Audio Player', AUDIO_PLAYER_TEMPLATES)
export const IMAGE_COMPARISON_PANEL_WITH_VARIATIONS = createMediaPanel('image-comparison', 'Image Comparison', IMAGE_COMPARISON_TEMPLATES)
export const MEDIA_UPLOAD_PANEL_WITH_VARIATIONS = createMediaPanel('media-upload', 'Media Upload', MEDIA_UPLOAD_TEMPLATES)
export const SLIDESHOW_PANEL_WITH_VARIATIONS = createMediaPanel('slideshow', 'Slideshow', SLIDESHOW_TEMPLATES)
